version: '3.1'

services:
  mongo:
    image: mongo:6
    container_name: resiliencia
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    restart: always
    ports:
      - "27017:27017"
  mongo-test:
    image: mongo:6
    container_name: resiliencia-test
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    restart: always
    ports:
      - "27018:27017"


